###############################################################################
## FMCOMMS2/4 on PolarFire MPF300 Splash Kit - Top-level build script
###############################################################################
#
# PolarFire port of projects/fmcomms2/axau15/build_all.tcl: same system
# (NEORV32 RISC-V CPU + axi_ad9361 + SmartHLS adapters + CDC FIFOs + QPSK
# snapshot BRAM, same address map and GPIO map so the ad9361_no-os software
# in deps/neorv32/sw/ad9361_no-os runs unmodified), rebuilt as a Libero
# SmartDesign ("Top") for the MPF300-SPLASH-KIT device.
#
# Differences from the axau15/Vivado script it mirrors:
#   - Libero batch flow; build_all is invoked automatically at the end of
#     this file. Run headless:
#       cd deps/hdl/projects/fmcomms2/mpf300
#       /media/fpgadev/Dev_Tools/Microchip/run_libero.sh \
#           SCRIPT:build_all.tcl LOGFILE:build_all.log
#     or from the Libero GUI via Project -> Execute Script.
#   - CPU/AXI/adapter fabric domain is 125 MHz (SmartHLS adapters are built
#     for CLOCK_PERIOD 8), generated by a PF_CCC PLL from the board's
#     50 MHz oscillator (ball H7). axau15 used 150 MHz; the NEORV32
#     CLOCK_FREQUENCY generic is set to 125 MHz so UART baud etc. are
#     correct without software changes.
#   - Vivado SmartConnect / BRAM controller / axis_data_fifo / proc_sys_reset
#     are replaced by the blocks in ./hdl, built on third-party open-source
#     components in deps/:
#       axi_1to3_decoder  -> PULP axi_lite_xbar        (deps/axi)
#       axis_async_fifo   -> open-logic olo_base_fifo_async (deps/open-logic,
#                            VHDL; 512x41 -> 2x LSRAM per FIFO, see the
#                            BRAM-strip note in hdl/axis_async_fifo.v)
#       sys_ctrl,
#       lclk_reset_sync   -> open-logic olo_base_reset_gen / olo_base_cc_bits
#                                                      (deps/open-logic, VHDL)
#       axi_bram_32k, dac_hold, refclk_ibuf: project-local plain HDL
#   - The generated Libero project lands in ./proj (rebuilt every run).
#
# IP vault: PF_CCC / PF_INIT_MONITOR are generated from the offline
# MegaVault (change_vault_location below) — the online repository is not
# reachable from this machine.
#
###############################################################################

###############################################################################
# Project configuration (global variables)
###############################################################################

variable project_name "fmcomms2_mpf300"
# Libero identifies the device by family/die/package rather than a single
# Vivado-style part string. MPF300T = the Splash Kit device
# (MPF300T-1FCG484E per the kit QuickStart, production silicon: the board's
# IDCODE 0x5F8131CF reads back as production MPF300(T|TS|...), and the
# programmer refuses a bitstream built for the MPF300TS_ES eval die used
# here previously). The Silver license covers MPF300T -- "Your Kit will
# work with Silver License" (QuickStart p.4); note new_project's
# rejected-die error message lists neither MPF300T nor MPF300TS_ES even
# though both are accepted.
variable family "PolarFire"
variable die "MPF300T"
variable pkg "FCG484"
variable speed "-1"
variable part_range "EXT"
variable project_dir [file normalize [file dirname [info script]]]
variable top_level_bd_name "Top"

variable megavault "/media/fpgadev/Dev_Tools/Microchip/MegaVault/Libero_SoC_v2025.2_MegaVault"
variable PF_CCC_version "2.2.222"
variable PF_INIT_MONITOR_version "2.0.308"

###############################################################################
# Block design component names
###############################################################################

# NEORV32 CPU and infrastructure
variable neorv32_cpu "NEORV32_RISC_V"
variable clk_gen "clk_gen"
variable init_monitor "init_monitor"
variable sys_ctrl_i "sys_ctrl_0"
variable lclk_rst "lclk_reset_sync_0"

# AXI fabric and BRAM
variable axi_cpu_interconnect "axi_cpu_interconnect"
variable qpsk_snapshot_bram "qpsk_snapshot_bram"

# AD9361 core and datapath
variable axi_ad9361 "axi_ad9361_0"
variable axi_ad9361_adapter "axi_ad9361_adapter_0"
variable dac_hold_i "dac_hold_0"

# AXI-Lite to Streaming adapter bridge (125 MHz domain)
variable axi_streaming_adapter "axi_streaming_adapter_0"

# AXI-Stream CDC FIFOs (125 MHz <-> l_clk)
variable cdc_tx_fifo "ad9361_cdc_tx_fifo"
variable cdc_rx_fifo "ad9361_cdc_rx_fifo"

###############################################################################
# Source locations
###############################################################################

variable repo_root [file normalize [file join $project_dir .. .. .. .. ..]]
variable lib_dir "$repo_root/deps/hdl/library"
variable ip_dir "$lib_dir/axi_ad9361"
variable neorv32_home "$repo_root/deps/neorv32"
variable hls_ad9361_dir "$repo_root/src/axi_ad9361_adapter_microchip"
variable hls_stream_dir "$repo_root/src/axi_lite_to_streaming_adapter_microchip"

# vendor-neutral ADI library modules

variable common_files {
    ad_addsub.v
    ad_datafmt.v
    ad_dds.v
    ad_dds_1.v
    ad_dds_2.v
    ad_dds_cordic_pipe.v
    ad_dds_sine.v
    ad_dds_sine_cordic.v
    ad_iqcor.v
    ad_pnmon.v
    ad_pps_receiver.v
    ad_rst.v
    ad_tdd_control.v
    up_adc_channel.v
    up_adc_common.v
    up_axi.v
    up_clock_mon.v
    up_dac_channel.v
    up_dac_common.v
    up_delay_cntrl.v
    up_tdd_cntrl.v
    up_xfer_cntrl.v
    up_xfer_status.v
}

variable core_files {
    axi_ad9361.v
    axi_ad9361_rx.v
    axi_ad9361_rx_channel.v
    axi_ad9361_rx_pnmon.v
    axi_ad9361_tdd.v
    axi_ad9361_tdd_if.v
    axi_ad9361_tx.v
    axi_ad9361_tx_channel.v
}

variable pf_files {
    axi_ad9361_lvds_if.v
    common/ad_data_in.v
    common/ad_data_out.v
    common/ad_data_clk.v
    common/ad_dcfilter.v
    common/ad_mul.v
}

variable helper_files {
    axi_1to3_decoder.sv
    axi_bram_32k.v
    axis_async_fifo.v
    sys_ctrl.v
    lclk_reset_sync.v
    dac_hold.v
    refclk_ibuf.v
    led_status.v
}

# PULP platform components (deps/common_cells v1.39.0, deps/axi v0.39.10):
# the AXI-Lite crossbar behind axi_1to3_decoder and the gray-code CDC FIFO
# behind axis_async_fifo. SystemVerilog, compiled into library work.

variable pulp_common_cells_files {
    cf_math_pkg.sv
    addr_decode_dync.sv
    addr_decode.sv
    spill_register_flushable.sv
    spill_register.sv
    fifo_v3.sv
    lzc.sv
    rr_arb_tree.sv
    counter.sv
    delta_counter.sv
    stream_register.sv
    sync.sv
    binary_to_gray.sv
    gray_to_binary.sv
    cdc_fifo_gray.sv
}

variable pulp_axi_files {
    axi_pkg.sv
    axi_intf.sv
    axi_lite_demux.sv
    axi_lite_mux.sv
    axi_lite_to_axi.sv
    axi_err_slv.sv
    axi_lite_xbar.sv
}

# open-logic components (deps/open-logic, VHDL): reset generation and the
# pwr_dn bit synchronizer behind sys_ctrl / lclk_reset_sync.

variable olo_files {
    olo_base_pkg_attribute.vhd
    olo_base_pkg_array.vhd
    olo_base_pkg_math.vhd
    olo_base_pkg_logic.vhd
    olo_base_pkg_string.vhd
    olo_base_cc_bits.vhd
    olo_base_cc_reset.vhd
    olo_base_ram_sdp.vhd
    olo_base_reset_gen.vhd
    olo_base_fifo_async.vhd
}

###############################################################################
# Helpers
###############################################################################

# connect a flat list of {pin pin ?pin?} groups inside the top SmartDesign
proc sd_wire {groups} {
    global top_level_bd_name
    foreach group $groups {
        set quoted {}
        foreach p $group {
            lappend quoted "\"$p\""
        }
        sd_connect_pins -sd_name $top_level_bd_name -pin_names [join $quoted " "]
    }
}

proc sd_tie {pins value} {
    global top_level_bd_name
    foreach p $pins {
        sd_connect_pins_to_constant -sd_name $top_level_bd_name \
            -pin_names $p -value $value
    }
}

proc sd_promote {pins} {
    global top_level_bd_name
    foreach {pin port} $pins {
        sd_connect_pin_to_port -sd_name $top_level_bd_name \
            -pin_name $pin -port_name $port
    }
}

###############################################################################
# build_all
###############################################################################

proc build_all {} {
    # Import global variables
    global project_name family die pkg speed part_range
    global project_dir top_level_bd_name
    global megavault PF_CCC_version PF_INIT_MONITOR_version
    global neorv32_cpu clk_gen init_monitor sys_ctrl_i lclk_rst
    global axi_cpu_interconnect qpsk_snapshot_bram
    global axi_ad9361 axi_ad9361_adapter dac_hold_i
    global axi_streaming_adapter cdc_tx_fifo cdc_rx_fifo
    global repo_root lib_dir ip_dir neorv32_home hls_ad9361_dir hls_stream_dir
    global common_files core_files pf_files helper_files
    global pulp_common_cells_files pulp_axi_files olo_files

    puts ""
    puts "==============================================================================="
    puts "  FMCOMMS2/4 on MPF300 Splash Kit - Build Script"
    puts "==============================================================================="
    puts ""
    puts "  Project: $project_name"
    puts "  Part:    $die-$pkg ($speed, $part_range)"
    puts "  Dir:     $project_dir"
    puts ""

    ###########################################################################
    # NEORV32 software image (ad9361_no-os), same mechanism as axau15
    ###########################################################################

    set sw_app_dir "$neorv32_home/sw/ad9361_no-os"
    set prebuilt   "$sw_app_dir/neorv32_imem_image.vhd"
    set app_image  "$neorv32_home/rtl/core/neorv32_imem_image.vhd"

    if {[file exists $prebuilt]} {
        puts "INFO: Installing pre-built ad9361_no-os image..."
        file copy -force $prebuilt $app_image
    } else {
        puts ""
        puts "ERROR: Pre-built ad9361_no-os application image not found:"
        puts "         $prebuilt"
        puts ""
        puts "  To build it, run (with RISC-V GCC in PATH):"
        puts "    cd $sw_app_dir && make clean_all image"
        puts ""
        return -1
    }

    ###########################################################################
    # Offline IP vault (MegaVault)
    ###########################################################################

    # The MegaVault was registered with Libero at install time (see
    # LiberoConfig.txt: "INSTALLED MegaVault 2025.2"), so PF_CCC /
    # PF_INIT_MONITOR generate offline without further setup. If core
    # generation fails on another machine, point the vault at a MegaVault
    # via Project -> Vault/Repositories settings (change_vault_location).
    if {![file exists $megavault]} {
        puts "WARNING: MegaVault not found at $megavault; PF_CCC generation may fail"
    }

    ###########################################################################
    # Project creation
    ###########################################################################

    set proj_dir $project_dir/proj
    if {[file exists $proj_dir]} {
        file delete -force $proj_dir
    }

    puts "INFO: Creating project..."
    if {[catch {
        new_project -location $proj_dir -name $project_name \
            -project_description {FMCOMMS2 on MPF300 Splash Kit (NEORV32 + axi_ad9361 + SmartHLS adapters)} \
            -block_mode 0 -standalone_peripheral_initialization 0 \
            -instantiate_in_smartdesign 1 -ondemand_build_dh 1 \
            -use_relative_path 0 -linked_files_root_dir_env {} \
            -hdl {VERILOG} -family $family -die $die -package $pkg \
            -speed $speed -die_voltage {1.0} -part_range $part_range \
            -adv_options {}
    } result]} {
        puts "ERROR: Failed to create project: $result"
        return -1
    }

    # The PULP axi/common_cells sources are SystemVerilog (packages,
    # parameter type, always_ff/always_comb); the project default of
    # Verilog-2001 fails to parse them in Synplify.
    project_settings -verilog_mode {SYSTEM_VERILOG}

    ###########################################################################
    # Source import
    ###########################################################################

    # NEORV32 VHDL core into its 'neorv32' VHDL library
    puts "INFO: Importing NEORV32 (VHDL, library neorv32)..."
    add_library -library {neorv32}

    set fl [open "$neorv32_home/rtl/file_list_soc.f" r]
    set neorv32_files {}
    while {[gets $fl line] >= 0} {
        set line [string trim $line]
        if {$line eq ""} { continue }
        lappend neorv32_files [string map [list {$NEORV32_HOME} $neorv32_home] $line]
    }
    close $fl

    # NEORV32 fast-multiplier pipeline register: deps/neorv32 now carries the
    # CPU_FAST_MUL_REG generic (PR #1603 -- pipeline register on the DSP
    # multiplier; a 33x33 multiply is a 3-deep 18x18 MACC cascade on PolarFire
    # and the single upstream register left ~6.8 ns combinational, capping the
    # CPU domain near 112 MHz). It is enabled via CPU_FAST_MUL_REG => true in
    # hdl/neorv32_mpf300_top.vhd, so no local source override is needed.
    # neorv32_imem_rom.vhd is replaced by an mpf300-only wrapper (see below);
    # skip the mainline copy so the override is the only one in the project
    foreach f $neorv32_files {
        if {[file tail $f] eq "neorv32_imem_rom.vhd"} { continue }
        import_files -hdl_source $f
        add_file_to_library -library {neorv32} -file $proj_dir/hdl/[file tail $f]
    }

    # mpf300-only IMEM ROM wrapper: identical entity/behavior, but the memory is
    # a signal pinned with syn_romstyle="lsram". The mainline package-constant
    # read maps to a ~57k-LUT mux tree inside Synplify's automatic-compile-point
    # context jobs, which -retiming then grinds on for 30+ minutes before the
    # netlist is discarded; the attribute makes every mapping context extract
    # RAM1K20 blocks up front (synthesis drops from ~2 h to minutes).
    import_files -hdl_source $project_dir/hdl/neorv32_imem_rom.vhd
    add_file_to_library -library {neorv32} -file $proj_dir/hdl/neorv32_imem_rom.vhd

    # integration shell + XBUS-to-AXI4 bridge (library work), plus this
    # project's configuration wrapper (HDL+ cannot set VHDL boolean
    # generics, so the axau15 configuration is fixed in the wrapper)
    import_files -hdl_source $neorv32_home/rtl/system_integration/xbus2axi4_bridge.vhd
    import_files -hdl_source $neorv32_home/rtl/system_integration/neorv32_vivado_ip.vhd
    import_files -hdl_source $project_dir/hdl/neorv32_mpf300_top.vhd

    # ADI library + axi_ad9361 core + polarfire device interface
    puts "INFO: Importing axi_ad9361 (polarfire port)..."
    foreach f $common_files { import_files -hdl_source $lib_dir/common/$f }
    foreach f $core_files   { import_files -hdl_source $ip_dir/$f }
    foreach f $pf_files     { import_files -hdl_source $ip_dir/polarfire/$f }

    # SmartHLS adapters (RTL + shared RAM primitives, deduplicated by name)
    puts "INFO: Importing SmartHLS adapters..."
    import_files -hdl_source $hls_ad9361_dir/hls_output/rtl/axi_ad9361_adapter_axi_ad9361_adapter.v
    import_files -hdl_source $hls_stream_dir/hls_output/rtl/axi_lite_to_streaming_adapter_axi_lite_to_streaming_adapter.v

    set seen_prims {}
    foreach d [list $hls_ad9361_dir $hls_stream_dir] {
        foreach f [glob -nocomplain $d/hls_output/rtl/ram_primitives/*.v] {
            set base [file tail $f]
            if {[lsearch -exact $seen_prims $base] < 0} {
                lappend seen_prims $base
                import_files -hdl_source $f
            }
        }
    }

    # merged mem_init directory for the SmartHLS RAM init files (both
    # adapters share one MEM_INIT_DIR define; file names do not collide)
    file mkdir $proj_dir/mem_init
    foreach d [list $hls_ad9361_dir $hls_stream_dir] {
        foreach f [glob -nocomplain $d/hls_output/rtl/mem_init/*.mem] {
            file copy -force $f $proj_dir/mem_init/
        }
    }
    # (MEM_INIT_DIR synthesis define is set after set_root below;
    #  configure_tool needs a root module)

    # PULP platform sources (SystemVerilog, library work).
    #
    # Amalgamated into ONE generated file, packages first: Libero's
    # design-hierarchy-driven synthesis fileset silently drops files that
    # contain only SV packages (nothing instantiates a package), so
    # separately imported cf_math_pkg.sv / axi_pkg.sv never reach Synplify
    # and every dependent file fails with unknown-package cascades.
    # Keeping the packages in the same file as the modules that use them
    # guarantees they are compiled, and in the right order.
    puts "INFO: Importing PULP common_cells + axi (amalgamated)..."
    set pulp_all $proj_dir/pulp_sources.sv
    set fo [open $pulp_all w]
    puts $fo "// Generated by build_all.tcl -- amalgamated PULP platform sources"
    puts $fo "// (deps/common_cells v1.39.0, deps/axi v0.39.10). Do not edit;"
    puts $fo "// edit the pulp_*_files lists in build_all.tcl instead."
    foreach f $pulp_common_cells_files {
        set fi [open $repo_root/deps/common_cells/src/$f r]
        puts $fo "\n// ==== common_cells/src/$f ====\n"
        puts $fo [read $fi]
        close $fi
    }
    foreach f $pulp_axi_files {
        set fi [open $repo_root/deps/axi/src/$f r]
        puts $fo "\n// ==== axi/src/$f ====\n"
        puts $fo [read $fi]
        close $fi
    }
    close $fo
    import_files -hdl_source $pulp_all

    # The PULP sources reference `include "axi/*.svh" and
    # `include "common_cells/*.svh". Stage both include trees next to the
    # imported copies in proj/hdl: relative includes resolve against the
    # including file's own directory in both the Libero hierarchy parser
    # and Synplify.
    file mkdir $proj_dir/hdl/axi
    foreach f [glob $repo_root/deps/axi/include/axi/*.svh] {
        file copy -force $f $proj_dir/hdl/axi/
    }
    file mkdir $proj_dir/hdl/common_cells
    foreach f [glob $repo_root/deps/common_cells/include/common_cells/*.svh] {
        file copy -force $f $proj_dir/hdl/common_cells/
    }

    # open-logic sources (VHDL, library work)
    puts "INFO: Importing open-logic base components..."
    foreach f $olo_files {
        import_files -hdl_source $repo_root/deps/open-logic/src/base/vhdl/$f
    }

    # project-local helper blocks
    puts "INFO: Importing helper HDL..."
    foreach f $helper_files { import_files -hdl_source $project_dir/hdl/$f }

    # constraints
    import_files -sdc $project_dir/constraint/system.sdc
    import_files -io_pdc $project_dir/constraint/io.pdc

    build_design_hierarchy

    ###########################################################################
    # Generated cores: PF_CCC (50 -> 125 MHz), PF_INIT_MONITOR
    ###########################################################################

    puts "INFO: Generating PF_CCC (50 MHz -> 125 MHz)..."
    create_and_configure_core -core_vlnv Actel:SgCore:PF_CCC:$PF_CCC_version \
        -component_name {PF_CCC_C0} -params {\
        "GL0_0_IS_USED:true" \
        "GL0_0_FABCLK_USED:true" \
        "GL0_0_OUT_FREQ:125" \
        "GL0_1_IS_USED:false" \
        "GL1_0_IS_USED:false" \
        "GL2_0_IS_USED:false" \
        "GL3_0_IS_USED:false" \
        "PLL_IN_FREQ_0:50" \
    }

    puts "INFO: Generating PF_INIT_MONITOR..."
    create_and_configure_core \
        -core_vlnv Actel:SgCore:PF_INIT_MONITOR:$PF_INIT_MONITOR_version \
        -component_name {PF_INIT_MONITOR_C0} -params {}

    ###########################################################################
    # HDL+ cores (needed for generic/parameter configuration)
    ###########################################################################

    create_hdl_core -file $proj_dir/hdl/axi_ad9361.v \
        -module {axi_ad9361} -library {work} -package {}

    ###########################################################################
    # SmartDesign top level
    ###########################################################################

    puts "INFO: Building SmartDesign top level '$top_level_bd_name'..."
    set sd $top_level_bd_name
    create_smartdesign -sd_name $sd

    # clocking / init (reference enters via INBUF+CLKINT so the PLL is not
    # tied to a dedicated-pad corner; see hdl/refclk_ibuf.v)
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {refclk_ibuf} \
        -hdl_file {hdl/refclk_ibuf.v} -instance_name {refclk_ibuf_0}
    sd_instantiate_component -sd_name $sd -component_name {PF_CCC_C0} \
        -instance_name $clk_gen
    sd_instantiate_component -sd_name $sd -component_name {PF_INIT_MONITOR_C0} \
        -instance_name $init_monitor

    # system control / resets
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {sys_ctrl} \
        -hdl_file {hdl/sys_ctrl.v} -instance_name $sys_ctrl_i
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {lclk_reset_sync} \
        -hdl_file {hdl/lclk_reset_sync.v} -instance_name $lclk_rst

    # boot/bring-up status on the 8 user LEDs (see hdl/led_status.v)
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {led_status} \
        -hdl_file {hdl/led_status.v} -instance_name {led_status_0}

    # NEORV32 (axau15 configuration at 125 MHz, fixed inside the wrapper)
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {neorv32_mpf300_top} \
        -hdl_file {hdl/neorv32_mpf300_top.vhd} -instance_name $neorv32_cpu

    # AXI fabric + BRAM
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {axi_1to3_decoder} \
        -hdl_file {hdl/axi_1to3_decoder.sv} -instance_name $axi_cpu_interconnect
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {axi_bram_32k} \
        -hdl_file {hdl/axi_bram_32k.v} -instance_name $qpsk_snapshot_bram

    # AD9361 core (HDL+, axau15 parameters)
    sd_instantiate_hdl_core -sd_name $sd -hdl_core_name {axi_ad9361} \
        -instance_name $axi_ad9361
    sd_configure_core_instance -sd_name $sd -instance_name $axi_ad9361 \
        -params {\
        "ID:0" \
        "CMOS_OR_LVDS_N:0" \
        "TDD_DISABLE:1" \
        "DAC_DDS_TYPE:1" \
        "DAC_DDS_CORDIC_DW:14" \
        "ADC_INIT_DELAY:11" \
    } -validate_rules 0

    # SmartHLS adapters + DAC holding registers
    sd_instantiate_hdl_module -sd_name $sd \
        -hdl_module_name {axi_ad9361_adapter_top} \
        -hdl_file {hdl/axi_ad9361_adapter_axi_ad9361_adapter.v} \
        -instance_name $axi_ad9361_adapter
    sd_instantiate_hdl_module -sd_name $sd \
        -hdl_module_name {axi_lite_to_streaming_adapter_top} \
        -hdl_file {hdl/axi_lite_to_streaming_adapter_axi_lite_to_streaming_adapter.v} \
        -instance_name $axi_streaming_adapter
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {dac_hold} \
        -hdl_file {hdl/dac_hold.v} -instance_name $dac_hold_i

    # CDC FIFOs
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {axis_async_fifo} \
        -hdl_file {hdl/axis_async_fifo.v} -instance_name $cdc_tx_fifo
    sd_instantiate_hdl_module -sd_name $sd -hdl_module_name {axis_async_fifo} \
        -hdl_file {hdl/axis_async_fifo.v} -instance_name $cdc_rx_fifo

    ###########################################################################
    # Top-level ports
    ###########################################################################

    sd_promote [list \
        "refclk_ibuf_0:pad"             ref_clk_50mhz \
        "$sys_ctrl_i:ext_resetn"        sys_resetn \
        "$neorv32_cpu:uart0_rxd_i"      sys_uart_rx \
        "$neorv32_cpu:uart0_txd_o"      sys_uart_tx \
        "$neorv32_cpu:spi_clk_o"        spi_clk \
        "$neorv32_cpu:spi_dat_o"        spi_mosi \
        "$neorv32_cpu:spi_dat_i"        spi_miso \
        "$sys_ctrl_i:spi_csn_0"         spi_csn_0 \
        "$sys_ctrl_i:gpio_resetb"       gpio_resetb \
        "$sys_ctrl_i:gpio_sync"         gpio_sync \
        "$sys_ctrl_i:gpio_en_agc"       gpio_en_agc \
        "$sys_ctrl_i:gpio_ctl"          gpio_ctl \
        "$neorv32_cpu:gpio_i"           gpio_status \
        "$axi_ad9361:rx_clk_in_p"       rx_clk_in_p \
        "$axi_ad9361:rx_clk_in_n"       rx_clk_in_n \
        "$axi_ad9361:rx_frame_in_p"     rx_frame_in_p \
        "$axi_ad9361:rx_frame_in_n"     rx_frame_in_n \
        "$axi_ad9361:rx_data_in_p"      rx_data_in_p \
        "$axi_ad9361:rx_data_in_n"      rx_data_in_n \
        "$axi_ad9361:tx_clk_out_p"      tx_clk_out_p \
        "$axi_ad9361:tx_clk_out_n"      tx_clk_out_n \
        "$axi_ad9361:tx_frame_out_p"    tx_frame_out_p \
        "$axi_ad9361:tx_frame_out_n"    tx_frame_out_n \
        "$axi_ad9361:tx_data_out_p"     tx_data_out_p \
        "$axi_ad9361:tx_data_out_n"     tx_data_out_n \
        "$axi_ad9361:enable"            enable \
        "$axi_ad9361:txnrx"             txnrx \
        "led_status_0:led"              led \
    ]

    ###########################################################################
    # Clock and reset network
    ###########################################################################

    sd_wire [list \
        [list "refclk_ibuf_0:clk" "$clk_gen:REF_CLK_0"] \
        [list "$clk_gen:OUT0_FABCLK_0" "$sys_ctrl_i:clk" "$neorv32_cpu:clk" \
              "$axi_cpu_interconnect:aclk" "$qpsk_snapshot_bram:aclk" \
              "$axi_streaming_adapter:clk" "$cdc_tx_fifo:s_axis_aclk" \
              "$cdc_rx_fifo:m_axis_aclk" "$axi_ad9361:s_axi_aclk" \
              "$axi_ad9361:delay_clk" "$lclk_rst:clk_125"] \
        [list "$clk_gen:PLL_LOCK_0" "$sys_ctrl_i:pll_lock"] \
        [list "$init_monitor:DEVICE_INIT_DONE" "$sys_ctrl_i:init_done"] \
        [list "$init_monitor:SRAM_INIT_DONE" "$sys_ctrl_i:sram_init_done"] \
        [list "$sys_ctrl_i:sys_resetn" "$neorv32_cpu:resetn" \
              "$axi_cpu_interconnect:aresetn" "$qpsk_snapshot_bram:aresetn" \
              "$cdc_rx_fifo:m_axis_aresetn" "$lclk_rst:ext_resetn"] \
        [list "$sys_ctrl_i:sys_reset" "$axi_streaming_adapter:reset"] \
        [list "$sys_ctrl_i:aresetn_gated" "$axi_ad9361:s_axi_aresetn" \
              "$cdc_tx_fifo:s_axis_aresetn"] \
        [list "$sys_ctrl_i:pwr_dn" "$lclk_rst:pwr_dn"] \
        [list "$axi_ad9361:l_clk" "$axi_ad9361:clk" \
              "$axi_ad9361_adapter:clk" "$dac_hold_i:clk" "$lclk_rst:l_clk" \
              "$cdc_tx_fifo:m_axis_aclk" "$cdc_rx_fifo:s_axis_aclk"] \
        [list "$lclk_rst:lclk_reset" "$axi_ad9361_adapter:reset"] \
        [list "$lclk_rst:lclk_resetn" "$cdc_tx_fifo:m_axis_aresetn" \
              "$cdc_rx_fifo:s_axis_aresetn"] \
        [list "$neorv32_cpu:gpio_o" "$sys_ctrl_i:gpio_o"] \
        [list "$neorv32_cpu:spi_csn_o" "$sys_ctrl_i:spi_csn_i"] \
        [list "$sys_ctrl_i:up_enable" "$axi_ad9361:up_enable"] \
        [list "$sys_ctrl_i:up_txnrx" "$axi_ad9361:up_txnrx"] \
        [list "$axi_ad9361:dac_sync_out" "$axi_ad9361:dac_sync_in"] \
    ]

    ###########################################################################
    # NEORV32 m_axi  <->  decoder slave port
    ###########################################################################

    set axi_conn {}
    foreach s {awaddr awlen awsize awburst awprot awvalid awready
               wdata wstrb wlast wvalid wready bresp bvalid bready
               araddr arlen arsize arburst arprot arvalid arready
               rdata rresp rlast rvalid rready} {
        lappend axi_conn [list "$neorv32_cpu:m_axi_$s" "$axi_cpu_interconnect:s_$s"]
    }
    sd_wire $axi_conn

    ###########################################################################
    # decoder M0 <-> BRAM
    ###########################################################################

    set m0_conn {}
    foreach s {awaddr awvalid awready wdata wstrb wvalid wready
               bresp bvalid bready araddr arvalid arready
               rdata rresp rvalid rready} {
        lappend m0_conn [list "$axi_cpu_interconnect:m0_$s" "$qpsk_snapshot_bram:$s"]
    }
    sd_wire $m0_conn

    ###########################################################################
    # decoder M1 <-> axi_ad9361 s_axi (AXI4-Lite)
    ###########################################################################

    set m1_conn {}
    foreach s {awaddr awprot awvalid awready wdata wstrb wvalid wready
               bresp bvalid bready araddr arprot arvalid arready
               rdata rresp rvalid rready} {
        lappend m1_conn [list "$axi_cpu_interconnect:m1_$s" "$axi_ad9361:s_axi_$s"]
    }
    sd_wire $m1_conn

    ###########################################################################
    # decoder M2 <-> streaming adapter AXI4 subset
    ###########################################################################

    sd_wire [list \
        [list "$axi_cpu_interconnect:m2_awaddr"  "$axi_streaming_adapter:axi_aw_addr"] \
        [list "$axi_cpu_interconnect:m2_awlen"   "$axi_streaming_adapter:axi_aw_len"] \
        [list "$axi_cpu_interconnect:m2_awsize"  "$axi_streaming_adapter:axi_aw_size"] \
        [list "$axi_cpu_interconnect:m2_awburst" "$axi_streaming_adapter:axi_aw_burst"] \
        [list "$axi_cpu_interconnect:m2_awvalid" "$axi_streaming_adapter:axi_aw_valid"] \
        [list "$axi_cpu_interconnect:m2_awready" "$axi_streaming_adapter:axi_aw_ready"] \
        [list "$axi_cpu_interconnect:m2_wdata"   "$axi_streaming_adapter:axi_w_data"] \
        [list "$axi_cpu_interconnect:m2_wstrb"   "$axi_streaming_adapter:axi_w_strb"] \
        [list "$axi_cpu_interconnect:m2_wlast"   "$axi_streaming_adapter:axi_w_last"] \
        [list "$axi_cpu_interconnect:m2_wvalid"  "$axi_streaming_adapter:axi_w_valid"] \
        [list "$axi_cpu_interconnect:m2_wready"  "$axi_streaming_adapter:axi_w_ready"] \
        [list "$axi_cpu_interconnect:m2_bresp"   "$axi_streaming_adapter:axi_b_resp"] \
        [list "$axi_cpu_interconnect:m2_bvalid"  "$axi_streaming_adapter:axi_b_resp_valid"] \
        [list "$axi_cpu_interconnect:m2_bready"  "$axi_streaming_adapter:axi_b_resp_ready"] \
        [list "$axi_cpu_interconnect:m2_araddr"  "$axi_streaming_adapter:axi_ar_addr"] \
        [list "$axi_cpu_interconnect:m2_arlen"   "$axi_streaming_adapter:axi_ar_len"] \
        [list "$axi_cpu_interconnect:m2_arsize"  "$axi_streaming_adapter:axi_ar_size"] \
        [list "$axi_cpu_interconnect:m2_arburst" "$axi_streaming_adapter:axi_ar_burst"] \
        [list "$axi_cpu_interconnect:m2_arvalid" "$axi_streaming_adapter:axi_ar_valid"] \
        [list "$axi_cpu_interconnect:m2_arready" "$axi_streaming_adapter:axi_ar_ready"] \
        [list "$axi_cpu_interconnect:m2_rdata"   "$axi_streaming_adapter:axi_r_data"] \
        [list "$axi_cpu_interconnect:m2_rresp"   "$axi_streaming_adapter:axi_r_resp"] \
        [list "$axi_cpu_interconnect:m2_rlast"   "$axi_streaming_adapter:axi_r_last"] \
        [list "$axi_cpu_interconnect:m2_rvalid"  "$axi_streaming_adapter:axi_r_valid"] \
        [list "$axi_cpu_interconnect:m2_rready"  "$axi_streaming_adapter:axi_r_ready"] \
    ]

    ###########################################################################
    # axi_ad9361 <-> HLS adapter datapath (l_clk domain)
    ###########################################################################

    set adc_conn {}
    foreach ch {i0 q0 i1 q1} {
        lappend adc_conn [list "$axi_ad9361:adc_data_$ch"   "$axi_ad9361_adapter:adc_data_$ch"]
        lappend adc_conn [list "$axi_ad9361:adc_valid_$ch"  "$axi_ad9361_adapter:adc_valid_$ch"]
        lappend adc_conn [list "$axi_ad9361:adc_enable_$ch" "$axi_ad9361_adapter:adc_enable_$ch"]
        lappend adc_conn [list "$axi_ad9361:dac_valid_$ch"  "$axi_ad9361_adapter:dac_valid_$ch"]
        lappend adc_conn [list "$axi_ad9361:dac_enable_$ch" "$axi_ad9361_adapter:dac_enable_$ch"]
        lappend adc_conn [list "$axi_ad9361_adapter:dac_data_${ch}_write_en"   "$dac_hold_i:dac_data_${ch}_write_en"]
        lappend adc_conn [list "$axi_ad9361_adapter:dac_data_${ch}_write_data" "$dac_hold_i:dac_data_${ch}_write_data"]
        lappend adc_conn [list "$dac_hold_i:dac_data_$ch" "$axi_ad9361:dac_data_$ch"]
    }
    lappend adc_conn [list "$axi_ad9361_adapter:dac_dunf_write_en"   "$dac_hold_i:dac_dunf_write_en"]
    lappend adc_conn [list "$axi_ad9361_adapter:dac_dunf_write_data" "$dac_hold_i:dac_dunf_write_data"]
    lappend adc_conn [list "$dac_hold_i:dac_dunf" "$axi_ad9361:dac_dunf"]
    sd_wire $adc_conn

    ###########################################################################
    # AXI-Stream paths through the CDC FIFOs
    #   TX: streaming adapter (125 MHz) -> tx_fifo -> HLS adapter (l_clk)
    #   RX: HLS adapter (l_clk) -> rx_fifo -> streaming adapter (125 MHz)
    ###########################################################################

    set axis_conn {}
    foreach s {data keep strb last valid ready} {
        lappend axis_conn [list "$axi_streaming_adapter:tx_stream_$s" "$cdc_tx_fifo:s_axis_t$s"]
        lappend axis_conn [list "$cdc_tx_fifo:m_axis_t$s" "$axi_ad9361_adapter:tx_stream_$s"]
        lappend axis_conn [list "$axi_ad9361_adapter:rx_stream_$s" "$cdc_rx_fifo:s_axis_t$s"]
        lappend axis_conn [list "$cdc_rx_fifo:m_axis_t$s" "$axi_streaming_adapter:rx_stream_$s"]
    }
    sd_wire $axis_conn

    ###########################################################################
    # Constant ties
    ###########################################################################

    # SmartHLS adapters run a new invocation every cycle; PLL kept powered
    sd_tie [list "$axi_ad9361_adapter:start" "$axi_streaming_adapter:start" \
        "$clk_gen:PLL_POWERDOWN_N_0"] VCC

    # LVDS configuration: CMOS receive inputs unused; FDD mode: tdd_sync low;
    # no overflow monitor: adc_dovf low (both consumers, as on axau15)
    sd_tie [list \
        "$axi_ad9361:rx_clk_in" \
        "$axi_ad9361:rx_frame_in" \
        "$axi_ad9361:rx_data_in" \
        "$axi_ad9361:tdd_sync" \
        "$axi_ad9361:adc_dovf" \
        "$axi_ad9361_adapter:adc_dovf" \
        "$axi_ad9361:up_adc_gpio_in" \
        "$axi_ad9361:up_dac_gpio_in" \
        "$axi_ad9361:gps_pps" \
    ] GND

    # (NEORV32 unused peripheral inputs are defaulted inside the wrapper)

    ###########################################################################
    # Generate, set root, associate constraints
    ###########################################################################

    puts "INFO: Generating SmartDesign component..."
    if {[catch {generate_component -component_name $sd} result]} {
        puts "ERROR: Failed to generate $sd: $result"
        return -1
    }

    build_design_hierarchy
    set_root -module "$sd\::work"

    # point Synplify at the merged SmartHLS RAM-init directory, and map
    # inferred ROMs to LSRAM instead of LUT logic (rom_map_logic defaults to
    # 1, which builds the 128 KB NEORV32 IMEM out of ~65k 4LUTs and caps the
    # CPU domain near 69 MHz; LSRAM contents are loaded at power-up by the
    # design-initialization flow via PF_INIT_MONITOR)
    # -include_path: the PULP `include trees are also staged in proj/hdl
    # (see source import), the explicit paths are belt-and-suspenders
    # -retiming: lets Synplify move the single NEORV32 fast-mul product
    # register into the 3-deep MACC cascade (33x33 -> 3x 18x18 WideMult);
    # without it the register sits at the head of the cascade and the
    # MACC->regfile writeback path misses 125 MHz by ~1.1 ns
    # -report_path 200: the Libero default of 4000 reported paths adds
    # per-optimization-pass overhead in the mapper for no analysis value
    # -automatic_compile_point 0: the Libero-default multiprocessing flow carves
    # the NEORV32 into compile points and re-maps the enclosing top view inside
    # a compile-point context job where ROM->LSRAM extraction (and the
    # syn_romstyle attribute) is ignored -- that job rebuilds the IMEM as a
    # ~57k-LUT mux tree and retimes it for 30+ minutes, then its netlist loses
    # to the real top-level mapping anyway. A single mapper job maps the whole
    # design (IMEM in RAM1K20s) in well under a minute.
    configure_tool -name {SYNTHESIZE} \
        -params "SYNPLIFY_OPTIONS:set_option -hdl_define -set MEM_INIT_DIR=\"$proj_dir/mem_init/\"; set_option -rom_map_logic 0; set_option -retiming 1; set_option -report_path 200; set_option -automatic_compile_point 0; set_option -include_path \"$repo_root/deps/axi/include;$repo_root/deps/common_cells/include\""

    # high-effort timing-driven P&R (default effort left ~1.1 ns on the
    # MACC->regfile path; most of that is in-macro delay, this buys the rest)
    configure_tool -name {PLACEROUTE} \
        -params {EFFORT_LEVEL:true} \
        -params {REPAIR_MIN_DELAY:true}

    organize_tool_files -tool {SYNTHESIZE} \
        -file $proj_dir/constraint/system.sdc \
        -module "$sd\::work" -input_type {constraint}
    organize_tool_files -tool {PLACEROUTE} \
        -file $proj_dir/constraint/system.sdc \
        -file $proj_dir/constraint/io/io.pdc \
        -module "$sd\::work" -input_type {constraint}
    organize_tool_files -tool {VERIFYTIMING} \
        -file $proj_dir/constraint/system.sdc \
        -module "$sd\::work" -input_type {constraint}

    ###########################################################################
    # Synthesis
    ###########################################################################

    puts "INFO: Running synthesis..."
    if {[catch {run_tool -name {SYNTHESIZE}} result]} {
        puts "ERROR: Synthesis failed: $result"
        return -1
    }

    puts ""
    puts "==============================================================================="
    puts "  Synthesis complete"
    puts "==============================================================================="
    puts "MPF300_FMCOMMS2_SYNTH_OK"

    ###########################################################################
    # Implementation (place & route)
    ###########################################################################

    puts "INFO: Running place and route..."
    if {[catch {run_tool -name {PLACEROUTE}} result]} {
        puts "ERROR: Place and route failed: $result"
        return -1
    }

    # Note: run_tool VERIFYTIMING succeeds as long as analysis runs; it does
    # NOT imply the constraints are met. Read the slack numbers in
    # proj/designer/Top/Top_max_timing_multi_corner.xml (or the GUI).
    puts "INFO: Running timing verification..."
    if {[catch {run_tool -name {VERIFYTIMING}} result]} {
        puts "WARNING: Timing verification failed to run: $result"
    } else {
        puts "MPF300_FMCOMMS2_TIMING_ANALYZED (check reports for slack)"
    }

    ###########################################################################
    # Bitstream generation (PolarFire G5 programming flow)
    #   GENERATEPROGRAMMINGDATA  - "Generate FPGA Array Data"
    #   GENERATE_INIT_DATA       - "Generate Design Initialization Data":
    #                              the NEORV32 IMEM (ad9361_no-os image) and the
    #                              other LSRAM contents are loaded at power-up via
    #                              PF_INIT_MONITOR, so the RAM-init data must be
    #                              baked into the bitstream.
    #   GENERATEPROGRAMMINGFILE  - "Generate Bitstream"
    ###########################################################################

    puts "INFO: Generating FPGA array (programming) data..."
    if {[catch {run_tool -name {GENERATEPROGRAMMINGDATA}} result]} {
        puts "ERROR: GENERATEPROGRAMMINGDATA failed: $result"
        return -1
    }

    # First pass generates designer/Top/Top_RAM.cfg (per-RAM init client
    # config, everything defaulted to sNVM). The content-bearing clients (the
    # NEORV32 IMEM image + SmartHLS adapter buffers, ~119 KB of data -> 263 KB
    # client) exceed the 54 KB sNVM and the MPF300 uPROM, so those clients
    # must live in the external SPI flash; the tool only reports the overflow
    # later, at bitstream generation. Retarget them and regenerate.
    puts "INFO: Generating design initialization data (first pass, writes RAM cfg)..."
    if {[catch {run_tool -name {GENERATE_INIT_DATA}} result]} {
        puts "ERROR: GENERATE_INIT_DATA failed: $result"
        return -1
    }

    set ram_cfg "$proj_dir/designer/Top/Top_RAM.cfg"
    set spi_cfg "$proj_dir/designer/Top/Top_RAM_spiflash.cfg"
    if {![file exists $ram_cfg]} {
        puts "ERROR: $ram_cfg not found; cannot retarget RAM init clients to SPI flash"
        return -1
    }
    set in  [open $ram_cfg r]
    set out [open $spi_cfg w]
    set block ""
    while {[gets $in line] >= 0} {
        if {[string match "set_client*" $line]} {
            if {$block ne ""} {
                if {[string first "INFERRED_INITIALIZED" $block] >= 0} {
                    regsub -all {storage_type \{SNVM\}} $block {storage_type {SPI}} block
                }
                puts -nonewline $out $block
            }
            set block "$line\n"
        } elseif {$block ne ""} {
            append block "$line\n"
        }
    }
    if {$block ne ""} {
        if {[string first "INFERRED_INITIALIZED" $block] >= 0} {
            regsub -all {storage_type \{SNVM\}} $block {storage_type {SPI}} block
        }
        puts -nonewline $out $block
    }
    close $in
    close $out

    # The RAM-client storage_type token for SPI flash is literally {SPI}
    # (captured from a GUI-written RAM.cfg). {SPIFLASH} and {SPI_FLASH} are
    # silently accepted by configure_ram but drop the client from the
    # stage-3 assembly -- the SPI image then contains only the placeholder.
    #
    # ORDER MATTERS: the SPI flash memory map must be configured BEFORE
    # configure_ram assigns clients to SPI storage. With the memory
    # undefined, Libero accepts the configure_ram call but silently DROPS the
    # initialized clients -- the second GENERATE_INIT_DATA then reports only
    # "Stage 1 ... added to sNVM" (no stage-3 client), the SPI image contains
    # nothing but the placeholder, and the board boots with an uninitialized
    # IMEM (CPU runs garbage, console stays silent).
    #
    # SPI Flash memory-map configuration (cfg/spiflash.cfg, ships in repo):
    # memory size 134217728 -- the field is in BYTES, so this is 128 MiB,
    # the size of the 1 Gb MT25QL01GB -- plus one 256-byte STATIC_FILL
    # placeholder client at 8388608 decimal = 8 MiB.
    # The placeholder's address MUST stay clear of the stage-3 design-init
    # client, which Libero places at flash offset 0x400 and which is ~263 KB
    # for this design (0x400..~0x40C60): a placeholder inside that span makes
    # Libero silently drop the init client. The -start_address field parses
    # as DECIMAL: a 0x-prefixed value is coerced to 0 (warning only), which
    # would land the placeholder at address 0 -- on top of the 0x400 client --
    # so the address is written in plain decimal here (8388608, not 0x800000).
    #
    # The placeholder also works around a Libero 2025.2 batch-mode bug: with
    # zero user clients in the SPI Flash map,
    # isSpiFlashConfiguredAndValid() (libitlfpro.so) raises the "There are
    # no SPI Flash clients selected for programming" dialog via
    # App::GetMainFrameWidget(), which is NULL in batch mode -> SIGSEGV in
    # GENERATE_SPI_FLASH_IMAGE and in the bitstream generator's internal
    # SPI-image invocation. STATIC_FILL writes the flash's erased state, so
    # the placeholder is electrically a no-op. If cfg/spiflash.cfg is
    # missing, the SPI-flash image steps are skipped (fabric+sNVM job only).
    set spiflash_cfg "$project_dir/cfg/spiflash.cfg"
    set have_spiflash_cfg [file exists $spiflash_cfg]
    if {$have_spiflash_cfg} {
        puts "INFO: Applying SPI Flash memory configuration..."
        # Hard error: if this call fails the whole SPI branch is skipped and
        # the build would quietly produce a fabric+sNVM-only job with no
        # firmware anywhere (silent console on the board).
        if {[catch {configure_spiflash -cfg_file $spiflash_cfg} result]} {
            puts "ERROR: configure_spiflash failed: $result"
            puts "ERROR: check cfg/spiflash.cfg -- set_spi_flash_memory_size"
            puts "ERROR: is in BYTES (134217728 = 128 MiB = the 1 Gb"
            puts "ERROR: MT25QL01GB)."
            return -1
        }
    }

    # Now that the SPI flash memory exists, retarget the initialized RAM
    # clients onto it (see the ORDER MATTERS note above).
    puts "INFO: Retargeting initialized RAM clients to SPI flash..."
    if {[catch {configure_ram -cfg_file $spi_cfg} result]} {
        puts "ERROR: configure_ram failed: $result"
        return -1
    }

    # SPI client at 0x400, plaintext, divider 2 (40 MHz System Controller SPI)
    if {[catch {configure_design_initialization_data \
            -second_stage_start_address {0x00000000} \
            -third_stage_spi_start_address {0x00000400} \
            -third_stage_spi_type {SPIFLASH_NO_BINDING_PLAINTEXT} \
            -third_stage_spi_clock_divider {2} \
            -init_timeout {128} \
            -broadcast_RAMs {0}} result]} {
        puts "WARNING: configure_design_initialization_data: $result"
    }

    puts "INFO: Regenerating design initialization data (SPI-flash placement)..."
    if {[catch {run_tool -name {GENERATE_INIT_DATA}} result]} {
        puts "ERROR: GENERATE_INIT_DATA (SPI-flash placement) failed: $result"
        return -1
    }

    # Diagnostics: report which init-stage artifacts exist. A stage-3 client
    # hosted in SPI flash does not produce Top_init_stage_2_3_assembly.txt
    # (that file is written for sNVM-hosted stages), so its absence here is
    # not conclusive -- the real check is the SPI image size, further below.
    foreach f {Top_init_stage_1_assembly.txt Top_init_stage_2_3_assembly.txt \
               Top_init_all_stages.mem} {
        set p "$proj_dir/designer/Top/$f"
        if {[file exists $p]} {
            puts "INFO: init artifact $f: [file size $p] bytes"
        } else {
            puts "INFO: init artifact $f: (absent)"
        }
    }

    puts "INFO: Generating bitstream..."
    if {[catch {run_tool -name {GENERATEPROGRAMMINGFILE}} result]} {
        puts "ERROR: GENERATEPROGRAMMINGFILE (bitstream) failed: $result"
        return -1
    }
    puts "MPF300_FMCOMMS2_BITSTREAM_OK"

    ###########################################################################
    # Export deployment artifacts (see program_board.tcl for programming)
    #   <export>/fmcomms2_mpf300.job     - FlashPro Express job: fabric + sNVM
    #                                      bitstream AND the SPI-flash image
    #                                      (stage-3 RAM-init client with the
    #                                      NEORV32 firmware) in one bundle
    #   <export>/fmcomms2_mpf300_spi.bin - standalone SPI-flash image
    #                                      (MT25QL01GB, the Splash Kit flash)
    ###########################################################################

    set export_dir "$proj_dir/export"
    file mkdir $export_dir

    if {$have_spiflash_cfg} {
        # Full deployment bundle: SPI flash image + job with both memories
        puts "INFO: Generating SPI flash image..."
        if {[catch {run_tool -name {GENERATE_SPI_FLASH_IMAGE}} result]} {
            puts "ERROR: GENERATE_SPI_FLASH_IMAGE failed: $result"
            return -1
        }

        # The SPI image must carry the stage-3 fabric-RAM init client (the
        # NEORV32 firmware, ~263 KB for this design). If it is tiny, only the
        # placeholder client made it in: the board would boot with an
        # uninitialized IMEM and a silent console. Fail loudly rather than
        # ship a dud image.
        set spi_img "$proj_dir/designer/Top/Top_spi_flash.bin"
        if {[file exists $spi_img]} {
            set spi_sz [file size $spi_img]
            puts "INFO: SPI flash image: $spi_sz bytes"
            if {$spi_sz < 200000} {
                puts "ERROR: SPI flash image is only $spi_sz bytes -- the"
                puts "ERROR: stage-3 init client (NEORV32 firmware image) is"
                puts "ERROR: missing. Do not program: the CPU would boot from"
                puts "ERROR: uninitialized IMEM (silent UART console)."
                return -1
            }
        } else {
            puts "ERROR: $spi_img was not generated -- the SPI flash image"
            puts "ERROR: (with the NEORV32 firmware) does not exist. Do not"
            puts "ERROR: program: the CPU would boot from uninitialized IMEM."
            return -1
        }

        puts "INFO: Exporting FlashPro Express programming job (fabric+sNVM+SPI)..."
        if {[catch {export_prog_job \
                -job_file_name {fmcomms2_mpf300} \
                -export_dir $export_dir \
                -bitstream_file_type {TRUSTED_FACILITY} \
                -bitstream_file_components {FABRIC SNVM} \
                -design_bitstream_format {PPD} \
                -program_design 1 \
                -program_spi_flash 1} result]} {
            puts "ERROR: export_prog_job failed: $result"
            return -1
        }

        # (-spiflash_device is not accepted for BIN-format exports)
        puts "INFO: Exporting standalone SPI flash image..."
        if {[catch {export_spiflash_image \
                -file_name {fmcomms2_mpf300_spi} \
                -export_dir $export_dir \
                -format {BIN}} result]} {
            puts "ERROR: export_spiflash_image failed: $result"
            return -1
        }
    } else {
        puts "INFO: No cfg/spiflash.cfg captured yet -- exporting fabric+sNVM job only."
        puts "INFO: SPI-flash image generation needs the one-time GUI configuration"
        puts "INFO: (see comment above the configure_spiflash call in this script)."
        puts "INFO: Exporting FlashPro Express programming job (fabric+sNVM)..."
        if {[catch {export_prog_job \
                -job_file_name {fmcomms2_mpf300} \
                -export_dir $export_dir \
                -bitstream_file_type {TRUSTED_FACILITY} \
                -bitstream_file_components {FABRIC SNVM} \
                -design_bitstream_format {PPD} \
                -program_design 1 \
                -program_spi_flash 0} result]} {
            puts "ERROR: export_prog_job failed: $result"
            return -1
        }
    }

    puts "  Export dir: $export_dir"
    puts "MPF300_FMCOMMS2_EXPORT_OK"

    puts ""
    puts "==============================================================================="
    puts "  Build complete!"
    puts "==============================================================================="
    puts ""
    puts "  Project saved to: $proj_dir/$project_name.prjx"
    puts "  Open in the Libero GUI to continue working manually."
    puts ""
    puts "MPF300_FMCOMMS2_PNR_OK"

    return 0
}
# End of build_all procedure

build_all
