#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# FMCOMMS2 on Ti375C529 - top-level block diagram generator.
#
# Efinity has no SmartDesign/IPI canvas: hdl/system_top.v is plain
# structural Verilog. This script is the replacement for the "maintained,
# always-current block diagram" the other two ports get from their vendor
# GUIs: it declares the top level as data (BLOCKS/NETS, the same
# information a SmartDesign Tcl script encodes) and renders it with
# graphviz. build_all.sh regenerates the SVG on every build, so diagram
# drift is structurally impossible.
#
#   python3 scripts/gen_top.py        -> doc/system_top.svg (+ .png if
#                                        graphviz supports it)
#
# Colors: 125 MHz domain blue, l_clk (61.44 MHz) domain orange, CDC
# purple, Interface Designer periphery dashed gray.
# ---------------------------------------------------------------------------

import os
import shutil
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJ_DIR = os.path.dirname(SCRIPT_DIR)
DOC_DIR = os.path.join(PROJ_DIR, "doc")

# instance, module, clock-domain
BLOCKS = [
    ("neorv32_risc_v",        "neorv32_ti375_top",     "sys"),
    ("axi_cpu_interconnect",  "axi_1to3_decoder",      "sys"),
    ("qpsk_snapshot_bram",    "axi_bram_32k",          "sys"),
    ("axi_streaming_adapter", "axi_lite_to_streaming_adapter_top", "sys"),
    ("sys_ctrl_0",            "sys_ctrl",              "sys"),
    ("ad9361_cdc_tx_fifo",    "axis_async_fifo",       "cdc"),
    ("ad9361_cdc_rx_fifo",    "axis_async_fifo",       "cdc"),
    ("lclk_reset_sync_0",     "lclk_reset_sync",       "cdc"),
    ("axi_ad9361_0",          "axi_ad9361 (efinix lvds_if)", "lclk"),
    ("axi_ad9361_adapter_0",  "axi_ad9361_adapter_top", "lclk"),
    ("dac_hold_0",            "dac_hold",              "lclk"),
    ("periphery",             "Interface Designer:\\nsys_pll 125M | lvds_pll 61.44M 0/90\\n8x LVDS RX | 8x LVDS TX | GPIO", "peri"),
]

# driver, receiver, label
NETS = [
    ("neorv32_risc_v",        "axi_cpu_interconnect",  "AXI4 (XBUS bridge)"),
    ("axi_cpu_interconnect",  "qpsk_snapshot_bram",    "M0 0xC000_0000"),
    ("axi_cpu_interconnect",  "axi_ad9361_0",          "M1 0x44A0_0000 AXI-Lite"),
    ("axi_cpu_interconnect",  "axi_streaming_adapter", "M2 0x44A1_0000"),
    ("axi_streaming_adapter", "ad9361_cdc_tx_fifo",    "AXIS TX"),
    ("ad9361_cdc_tx_fifo",    "axi_ad9361_adapter_0",  "AXIS TX (l_clk)"),
    ("axi_ad9361_adapter_0",  "ad9361_cdc_rx_fifo",    "AXIS RX (l_clk)"),
    ("ad9361_cdc_rx_fifo",    "axi_streaming_adapter", "AXIS RX"),
    ("axi_ad9361_0",          "axi_ad9361_adapter_0",  "adc i/q 4ch"),
    ("axi_ad9361_adapter_0",  "dac_hold_0",            "dac write"),
    ("dac_hold_0",            "axi_ad9361_0",          "dac i/q 4ch"),
    ("sys_ctrl_0",            "neorv32_risc_v",        "sys_resetn"),
    ("sys_ctrl_0",            "axi_ad9361_0",          "aresetn_gated / up_enable / up_txnrx"),
    ("sys_ctrl_0",            "lclk_reset_sync_0",     "pwr_dn"),
    ("lclk_reset_sync_0",     "axi_ad9361_adapter_0",  "lclk_reset"),
    ("neorv32_risc_v",        "sys_ctrl_0",            "gpio_o[15:0] / spi_csn"),
    ("periphery",             "axi_ad9361_0",          "l_clk, lock, rx 2-bit words"),
    ("axi_ad9361_0",          "periphery",             "tx 2-bit words, enable, txnrx"),
    ("periphery",             "neorv32_risc_v",        "clk_125mhz, uart, spi, gpio_status"),
]

COLORS = {
    "sys":  ("#dbe9f9", "#2c5f96"),   # 125 MHz domain
    "lclk": ("#fbe5c8", "#a96017"),   # l_clk 61.44 MHz domain
    "cdc":  ("#e6dcf0", "#5b3a86"),   # CDC blocks
    "peri": ("#eeeeee", "#666666"),   # configured periphery
}


def emit_dot():
    lines = [
        "digraph system_top {",
        '  rankdir=LR; fontname="Helvetica"; splines=true;',
        '  node [shape=box, style="rounded,filled", fontname="Helvetica",'
        ' fontsize=11];',
        '  edge [fontname="Helvetica", fontsize=9, color="#555555"];',
        '  label="fmcomms2 / ti375c529 - system_top (generated by'
        ' scripts/gen_top.py)"; labelloc=t;',
    ]
    for inst, mod, dom in BLOCKS:
        fill, border = COLORS[dom]
        style = 'style="rounded,filled,dashed"' if dom == "peri" else \
                'style="rounded,filled"'
        lines.append(
            f'  "{inst}" [label="{inst}\\n({mod})", fillcolor="{fill}",'
            f' color="{border}", {style}];')
    for drv, rcv, lbl in NETS:
        dashed = ', style=dashed' if "periphery" in (drv, rcv) else ""
        lines.append(f'  "{drv}" -> "{rcv}" [label="{lbl}"{dashed}];')
    lines.append("}")
    return "\n".join(lines)


def main():
    os.makedirs(DOC_DIR, exist_ok=True)
    dot_file = os.path.join(DOC_DIR, "system_top.dot")
    with open(dot_file, "w") as f:
        f.write(emit_dot())

    dot = shutil.which("dot")
    if dot is None:
        print(f"wrote {dot_file} (graphviz 'dot' not found; SVG skipped)")
        return
    for fmt in ("svg", "png"):
        out = os.path.join(DOC_DIR, f"system_top.{fmt}")
        subprocess.run([dot, f"-T{fmt}", dot_file, "-o", out], check=True)
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
